### ISSUE TITLE
Find article on proper controller layout.

### ISSUE THREAD

**Issue by J-Ceguerra** [nsigames/2016-s1t2-c41b-HackNSlash#31]
Please locate the article on controller action layouts.

**Comment by J-Ceguerra** [comment]
![untitled](https://cloud.githubusercontent.com/assets/18672981/15314016/ab4de2d2-1c52-11e6-9e1d-6cfaf23a88c7.png)

**Comment by hdsantos89** [comment]
http://blogs.unity3d.com/2016/04/12/developing-the-new-input-system-together-with-you/

**Comment by hdsantos89** [comment]
Time spent: 0:16

**Comment by hdsantos89** [comment]
https://blogs.msdn.microsoft.com/uk_faculty_connection/2014/12/02/adding-xbox-controller-support-and-input-to-your-unity3d-game/
